/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-10-24 05:35:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <title></title>\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\">\n");
      out.write("    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->\n");
      out.write("    <!-- build:css(.) styles/vendor.css -->\n");
      out.write("    <!-- bower:css -->\n");
      out.write("    <!-- endbower -->\n");
      out.write("    <!-- endbuild -->\n");
      out.write("    <!-- build:css(.tmp) styles/main.css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/stylesheets/main.css\">\n");
      out.write("    <!-- endbuild -->\n");
      out.write("  </head>\n");
      out.write("  <body ng-app=\"sraApp\">\n");
      out.write("    <!--[if lte IE 8]>\n");
      out.write("      <p class=\"browsehappy\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("    <!-- Add your site or application content here -->\n");
      out.write("    <div class=\"header\">\n");
      out.write("      <div class=\"navbar navbar-default\" role=\"navigation\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"navbar-header\">\n");
      out.write("\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#js-navbar-collapse\">\n");
      out.write("              <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <a class=\"navbar-brand\" href=\"#/\">sra</a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"js-navbar-collapse\">\n");
      out.write("\n");
      out.write("            <ul class=\"nav navbar-nav\">\n");
      out.write("              <li class=\"active\"><a href=\"#/\">Home</a></li>\n");
      out.write("              <li><a ng-href=\"#/about\">About</a></li>\n");
      out.write("              <li><a ng-href=\"#/\">Contact</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("    <div ng-view=\"\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"footer\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <p><span class=\"glyphicon glyphicon-heart\"></span> from the Yeoman team</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID -->\n");
      out.write("     <script>\n");
      out.write("       !function(A,n,g,u,l,a,r){A.GoogleAnalyticsObject=l,A[l]=A[l]||function(){\n");
      out.write("       (A[l].q=A[l].q||[]).push(arguments)},A[l].l=+new Date,a=n.createElement(g),\n");
      out.write("       r=n.getElementsByTagName(g)[0],a.src=u,r.parentNode.insertBefore(a,r)\n");
      out.write("       }(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n");
      out.write("\n");
      out.write("       ga('create', 'UA-XXXXX-X');\n");
      out.write("       ga('send', 'pageview');\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <!-- build:js(.) scripts/vendor.js -->\n");
      out.write("    <!-- bower:js -->\n");
      out.write("    <script src=\"bower_components/jquery/dist/jquery.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular/angular.js\"></script>\n");
      out.write("    <script src=\"bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-animate/angular-animate.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-cookies/angular-cookies.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-resource/angular-resource.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-route/angular-route.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-sanitize/angular-sanitize.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-touch/angular-touch.js\"></script>\n");
      out.write("    <!-- endbower -->\n");
      out.write("    <!-- endbuild -->\n");
      out.write("\n");
      out.write("        <!-- build:js({.tmp,app}) scripts/scripts.js -->\n");
      out.write("        <script src=\"scripts/app.js\"></script>\n");
      out.write("        <script src=\"scripts/controllers/main.js\"></script>\n");
      out.write("        <script src=\"scripts/controllers/about.js\"></script>\n");
      out.write("        <!-- endbuild -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
