/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-10-29 10:26:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <title></title>\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"bower_components/bootstrap/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles/stylesheets/include.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"bower_components/angular-material/angular-material.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"bower_components/bootstrap-datepicker-master/dist/css/bootstrap-datepicker.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"bower_components/bootstrap-timepicker/bootstrap-timepicker.min.css\">\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("  <body ng-app=\"sraApp\">\n");
      out.write("    <!--[if lte IE 8]>\n");
      out.write("      <p class=\"browsehappy\">You are using an <strong>outdated</strong> browser. Please <a href=\"http://browsehappy.com/\">upgrade your browser</a> to improve your experience.</p>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("    <!-- Add your site or application content here -->\n");
      out.write("    <div class=\"header\">\n");
      out.write("      <div class=\"navbar navbar-default\" role=\"navigation\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("          <div class=\"navbar-header\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"#/\">SRA</a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"logout-container\" ng-if=\"isUserLoggedIn == true && userName != ''\">\n");
      out.write("            <div class=\"logged-in-username\">{{userName}}</div>\n");
      out.write("            <span class=\"buttons-divider\"></span>\n");
      out.write("            <div class=\"logout-button-action\"><a ng-href=\"#\" ng-controller=\"LogoutController as logoutController\"\n");
      out.write("                                                 ng-click=\"logoutController.logout()\">Logout</a></div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"page-wrap\">\n");
      out.write("      <div class=\"wrapper\" ng-view=\"\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <footer class=\"site-footer\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <p>&copy; Copyright 2015, SRA.</p>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <script src=\"bower_components/jquery/dist/jquery.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular/angular.js\"></script>\n");
      out.write("    <script src=\"bower_components/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-animate/angular-animate.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-cookies/angular-cookies.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-resource/angular-resource.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-route/angular-route.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-aria/angular-aria.js\"></script>\n");
      out.write("    <script src=\"bower_components/angular-material/angular-material.js\"></script>\n");
      out.write("    <script src=\"bower_components/skype/skype-uri.js\"></script>\n");
      out.write("    <script src=\"bower_components/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.js\"></script>\n");
      out.write("    <script src=\"bower_components/bootstrap-timepicker/bootstrap-timepicker.min.js\"></script>\n");
      out.write("    <script src=\"bower_components/mockjax/jquery.mockjax.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"scripts/app.js\"></script>\n");
      out.write("    <script src=\"scripts/md5.js\"></script>\n");
      out.write("    <script src=\"scripts/controllers/login.js\"></script>\n");
      out.write("    <script src=\"scripts/controllers/main.js\"></script>\n");
      out.write("    <script src=\"scripts/controllers/detail.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
