/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-10-26 02:47:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<div class=\"container\">\n");
      out.write("  <div class=\"page-home\">\n");
      out.write("    <div ng-controller=\"CustomerListController as customerListCtrl\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-xs-12\">\n");
      out.write("          <div class=\"panel-card\">\n");
      out.write("            <div class=\"header-panel\">\n");
      out.write("              <h4>Customers List</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row m-0 filter-block\">\n");
      out.write("              <div class=\"col-sm-4\">\n");
      out.write("                <md-input-container>\n");
      out.write("                  <label>Search</label>\n");
      out.write("                  <input name=\"searchKey\" ng-model=\"customerListCtrl.searchKey\">\n");
      out.write("                </md-input-container>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-4\">\n");
      out.write("                <md-input-container>\n");
      out.write("                  <md-select ng-model=\"customerListCtrl.sortKey\" placeholder=\"Sort by\">\n");
      out.write("                    <md-option value=\"id\">Sort by Customer ID</md-option>\n");
      out.write("                    <md-option value=\"customername\">Sort by Customer Name</md-option>\n");
      out.write("                    <md-option value=\"productname\">Sort by Product</md-option>\n");
      out.write("                  </md-select>\n");
      out.write("                </md-input-container>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-sm-4 text-align-c xs-m-b-15\">\n");
      out.write("                <md-button class=\"md-raised refresh-btn-vertical-align\" ng-click=\"customerListCtrl.refreshList()\">Refresh List</md-button>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"row table-heading hidden-xs\">\n");
      out.write("        <div class=\"col-sm-3\">ID</div>\n");
      out.write("        <div class=\"col-sm-3\">NAME</div>\n");
      out.write("        <div class=\"col-sm-3\">PRODUCT</div>\n");
      out.write("        <div class=\"col-sm-3\">STATUS</div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"customer-list-block\">\n");
      out.write("        <div class=\"row custom-card\"\n");
      out.write("             ng-repeat=\"customer in customerListCtrl.customerList.data | filter: customerListCtrl.searchKey\n");
      out.write("             | orderBy: customerListCtrl.sortKey\"\n");
      out.write("             ng-click=\"customerListCtrl.openCustomerDetail(customer.id)\">\n");
      out.write("          <div class=\"col-sm-3\"><div class=\"xs-m-b-15\"><span class=\"circle-highlight\">{{customer.id}}</span></div></div>\n");
      out.write("          <div class=\"col-xs-12 visible-xs grid-label\">Name</div>\n");
      out.write("          <div class=\"col-sm-3\">{{customer.customername}}</div>\n");
      out.write("          <div class=\"col-xs-12 visible-xs grid-label\">Product</div>\n");
      out.write("          <div class=\"col-sm-3\">{{customer.productname}}</div>\n");
      out.write("          <div class=\"col-xs-12 visible-xs grid-label\">Status</div>\n");
      out.write("          <div class=\"col-sm-3\">{{customer.status}}</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
